name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup do NodeJS
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 16.13.2

      - name: Instalação do Mocha para teste
        run: |
          cd 03-DevOps_Basico/conversao-temperatura/src
          npm install -g mocha;
          npm install
